### ISSUE TITLE
Test en Actions

### ISSUE THREAD

**Issue by Ama-ya** [Ama-ya/practica_dwec_gestor_presupuesto#1]
Hola @pedroprieto, ¿es normal que me haga los test de todas las prácticas cada vez que subo cambios a GitHub?, pensaba que sólo haría los test relacionados.
¿Y tengo que hacer la Pull Request en cada práctica del mismo apartado o cuando termine las 3?
Un saludo,
Amaya

PD. Vale, ya he visto que lo de los test, es por el retraso que llevo.

**Comment by pedroprieto** [comment]
Buenas,

Sí, es normal que se ejecuten todos: lo que ocurre es que solo debes pasar los de la práctica correspondiente.

En la primera práctica, solo la PR al acabar los 3 apartados, como has visto :wink: 

Un saludo!!

**Comment by Ama-ya** [comment]
Gracias!
