### ISSUE TITLE
No pasa los test

### ISSUE THREAD

**Issue by Ama-ya** [Ama-ya/practica_dwec_gestor_presupuesto#2]
Hola @pedroprieto, he intentado varias maneras para pasar los test, incluso he copiado algunas funciones del archivo de solución, y me sigue dando error 8 de los test, muchos me pone el mismo problema, que this.anyadirEtiquetas no es una función, y creo que ni siquiera hace el test.
Voy a probar copiar todo el archivo de la solución literal a ver si encuentro la solución, no sé si es que estoy poniendo algo mal y no soy capaz de verlo.
Pego el primer error que me da, y los demás son el mismo tipo de error:

  1) Función CrearGasto y funcionamiento de objeto gasto
       CrearGasto: comprobación con fecha y etiquetas:
     TypeError: this.anyadirEtiquetas is not a function
      at new CrearGasto (file:///C:/Users/Amaia/source/repos/DWEC2324/practica_dwec_gestor_presupuesto/js/gestionPresupuesto.js:47:10)
      at Context.<anonymous> (file:///C:/Users/Amaia/source/repos/DWEC2324/practica_dwec_gestor_presupuesto/test/02_testIntroJSII.js:21:22)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17)

Un saludo,
Amaya

**Comment by pedroprieto** [comment]
Buenas,

Acabo de ver que has hecho la PR y que ya pasas los test. ¿Conseguiste encontrar el problema? Seguramente se debía a que no habías creado la función `anyadirEtiquetas` como método del constructor... O eso, o un error con alguna letra/mayúscula.

En cualquier caso, si tienes alguna duda dímelo.

Un saludo!!

**Comment by Ama-ya** [comment]
Sí estaba creada, y le di tantas vueltas ya que no se que era, pero bueno, ya salió. Gracias!
