### ISSUE TITLE
Interacción de JavaScript con HTML con errores

### ISSUE THREAD

**Issue by Ama-ya** [Ama-ya/practica_dwec_gestor_presupuesto#3]
Hola @pedroprieto, he subido la práctica pero me salen todos los campos undefined menos lo primero, y no sé porqué, ya lo he revisado y no consigo ver más.

Un saludo,
Amaya

**Comment by pedroprieto** [comment]
Buenas,

Tienes varios errores en el fichero `generarDatosEstaticos.js`:
- Los gastos no se tienen que generar así, sino individualmente y cada uno con `new gestionPresupuesto.CrearGasto`
  https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/77e670b815cf5cb8b84c4358f3bc0ed4dec31f28/js/generarDatosEstaticos.js#L12-L24
- La función `mostrarGastoWeb` admite como parámetro un gasto, no un array de gastos. En lugar del siguiente código, tienes que crear un bucle que itere sobre cada gasto devuelto por `listarGastos`:
  https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/77e670b815cf5cb8b84c4358f3bc0ed4dec31f28/js/generarDatosEstaticos.js#L33

Repasa el enunciado donde se especifica cómo crear ese fichero.

Un saludo y ánimo!!

**Comment by Ama-ya** [comment]
@pedroprieto , he modificado esos errores, ahora me pasa los test pero los datos filtrados me los muestra undefined, y la fecha me sale en formato timestamp.
Un saludo,
Amaya

**Comment by pedroprieto** [comment]
Perfecto pues. Está todo, ¿no? :clap:  Si es el caso, abre una Pull Request para la corrección. 

Un saludo!!

**Comment by Ama-ya** [comment]
Perdona @pedroprieto, que no me expliqué bien, los test de la tarea los pasa, la fecha y las etiquetas salen bien, pero me siguen saliendo datos undefined.
Un saludo y felices fiestas!
Amaya

**Comment by pedroprieto** [comment]
Buenas,

El problema está en estos bucles:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/68ebc5b399e33b6c5187d42755e2ee8e0257e794/js/generarDatosEstaticos.js#L33-L34

Utilizas la variable incorrecta: debes utilizar la variable de iteración, en este caso `gf1`, en lugar de `gastoFiltrado1`, dentro del bucle.

Tienes el mismo problema en todos los bucles de mostrar gastos filtrados.

Un saludo y felices fiestas!!

**Comment by Ama-ya** [comment]
Gracias @pedroprieto ahora sí, no conseguía verlo.
