### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by Ama-ya** [Ama-ya/practica_dwec_gestor_presupuesto#5]
Hola @pedroprieto, he hecho lo que he podido, sólo me pasa 3 test y no funciona todo. 
Me resulta muy complicado entender lo que se pide.

Un saludo,
Amaya

**Comment by pedroprieto** [comment]
Por partes:
- No debes añadir el formulario a `controlesprincipales`, sino al `div` que contiene el gasto. Así, en lugar de esto:
  https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8284cfd80ccff5c55a7368a069e9664a88db3fc2/js/gestionPresupuestoWeb.js#L376-L377
  puedes hacer:
  ```js
  let parent = enviar.target.parentNode;  // Elemento <div> que contiene la estructura del gasto
  parent.append(plantillaFormulario);
  ```
- Todo esto te sobra. Además, no debes llamar a `repintar`, porque entonces se eliminará el formulario que has añadido antes:
  https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8284cfd80ccff5c55a7368a069e9664a88db3fc2/js/gestionPresupuestoWeb.js#L391-L399
- Lo que te faltaría sería crear un manejador de eventos para el botón de `Enviar` del formulario de edición. Algo parecido a lo que has hecho con `Cancelar`, pero para hacer la edición:
  https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8284cfd80ccff5c55a7368a069e9664a88db3fc2/js/gestionPresupuestoWeb.js#L410-L411

Prueba con ello y a ver si lo sacas. Para más dudas, por aquí estoy. Un saludo!

**Comment by Ama-ya** [comment]
Gracias @pedroprieto , lo he corregido, pero no me actualiza los gastos editados, y no me genera gastos nuevos con el botón añadir gasto formulario. Lo he subido para que lo veas.

**Comment by Ama-ya** [comment]
Hola @pedroprieto, he corregido lo que me has puesto, sigue sin pasarme 3 apartados del test y no entiendo muy bien porqué, y me he dado cuenta de que con el botón Editar (formulario) en lugar de modificar el gasto, me genera uno nuevo a partir del gasto que estaba editando, claro porque estoy utilizando el mismo evento que para añadir un gasto nuevo. Y el botón Añadir gasto (formulario) sigue sin crear un gasto nuevo aún poniendo la línea 287.

Por cierto, cómo comentas el código para que salga aquí?
Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

Para comentar una línea, pulsa en la parte de la izquierda y selecciona "Copy permalink":
![imagen](https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/assets/7632447/5373732b-8bb2-4997-a0f0-577b46532b5d)

Así puedes pegar el enlace. Al poner la vista previa, verás que aparece la línea correspondiente.

Con respecto a tu duda, debes utilizar manejadores distintos, claro: uno para añadir y otro para editar.

La línea 287 está mal: pones directamente la función, pero esa función es un constructor.
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/3e6ba56a18fef0b1dab5671b99c92119d5115cc9/js/gestionPresupuestoWeb.js#L287

Debes crear el objeto basado en el constructor, tal como haces aquí:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/3e6ba56a18fef0b1dab5671b99c92119d5115cc9/js/gestionPresupuestoWeb.js#L391-L394

Está casi todo bien: la lógica que ahora tienes en "Editar" funciona bien para añadir, así que cámbiala de sitio y ponla en sustitución de la línea 287. Por último, crea un manejador propio para la edición.

Ánimo, que casi lo tienes!

**Comment by Ama-ya** [comment]
Gracias! 

He hecho varias modificaciones como me has dicho, me pasan 5 partes del test, falta una que me da error por el atributo disabled del button.gasto-editar-formulario que lo he puesto de varias maneras y sigue igual.

El botón Enviar del formulario que abre el botón Editar (formulario), ya funciona.

El que sigue sin funcionar es el botón Enviar del formulario que abre el botón Añadir gasto (formulario), que si dejo la siguiente línea sin comentar no hace nada y si la comento se cierra el formulario pero no añade el gasto:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8dab937088c9741b74c2f64f8b3d51090e677cba/js/gestionPresupuestoWeb.js#L288

Un saludo.
Amaya

**Comment by pedroprieto** [comment]
Buenas,

Esa línea sí que funciona: si te fijas, añade el gasto, pero en último lugar del listado. Te faltaría simplemente cerrar el formulario.

En cuanto al fallo del test, el problema está aquí:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8dab937088c9741b74c2f64f8b3d51090e677cba/js/gestionPresupuestoWeb.js#L348

Si cancelas la edición de cualquier gasto a partir del primero, se queda activo el botón:
![imagen](https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/assets/7632447/21448a97-f357-4348-aa03-38b045f4a720)

Ten en cuenta que botones de edición hay muchos, por lo que tienes que volver a activar el correspondiente, no el primero que se encuentre (tal como haces en tu código de la línea 348). Para ello, debes pasar una referencia al botón correspondiente aquí:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8dab937088c9741b74c2f64f8b3d51090e677cba/js/gestionPresupuestoWeb.js#L394-L396

Por ejemplo, mediante:
```js
 cancelarForm.botonEditar = enviar.target; // enviar.target será el botón de editar de ese gasto
```

`enviar.target` hará referencia al botón de "Editar (formulario)", tal como indicas aquí:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8dab937088c9741b74c2f64f8b3d51090e677cba/js/gestionPresupuestoWeb.js#L361

Por último, en vez de poner:
https://github.com/Ama-ya/practica_dwec_gestor_presupuesto/blob/8dab937088c9741b74c2f64f8b3d51090e677cba/js/gestionPresupuestoWeb.js#L348-L349

Deberás poner algo como:
```js
  this.botonEditar.removeAttribute('disabled');
```

De esta manera, `this.botonEditar` contendrá la referencia al botón de editar correspondiente.

Un saludo!!

**Comment by Ama-ya** [comment]
Pues he modificado lo del botón pero hay algo que se me escapa, como de dónde saco botonEditar, o es que lo estoy poniendo donde no es...

**Comment by Ama-ya** [comment]
Ah claro, genial,gracias!
